"""empty message

Revision ID: 232b1b8fc1bd
Revises: 
Create Date: 2023-03-16 21:11:23.480648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232b1b8fc1bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
